version: "3.8"
services:
    db:
        image: postgres:15.2
        container_name: local_pgdb
        restart: always
        ports:
            - "54320:5432"
        environment:
            POSTGRES_DB: book_store
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: root
        volumes:
            - local_pgdata:/var/lib/postgresql/data
    pgadmin:
            image: dpage/pgadmin4
            container_name: pgadmin4_container
            restart: always
            ports:
                - "5050:80"
            environment:
                PGADMIN_DEFAULT_EMAIL: root@gmail.com
                PGADMIN_DEFAULT_PASSWORD: root
            volumes:
                - pgadmin-data:/var/lib/pgadmin
    app:
        image: 'my-book-shop-app:latest'
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8080:8085"
        depends_on:
            - db
        environment:
            SPRING_DATASOURCE_URL: jdbc:postgresql://local_pgdb:5432/postgres
            SPRING_DATASOURCE_USERNAME: postgres
            SPRING_DATASOURCE_PASSWORD: root
volumes:
  local_pgdata:
  pgadmin-data: