server:
  port: 8085
  servlet:
    session:
      tracking-modes: cookie

auth:
  secret: secret

upload:
  path: D:/Personal projects/JavaSpring/uploads/book-covers
download:
  path: D:/Personal projects/JavaSpring/downloads/book-files

spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:54320/book_store
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  messages:
    basename: lang.messages
  web:
    resources:
      static-locations: classpath:/frontend/
  thymeleaf:
    prefix: classpath:/frontend/
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
  security:
    user:
      name: root
      password: root
  profiles:
    include: default,dev

  flyway:
    user: postgres
    password: root
    url: jdbc:postgresql://127.0.0.1:54320/book_store
    locations: classpath:/db/migration

  application:
    name: bookshop
  boot:
    admin:
      client:
        url: http://localhost:8080
        instance:
          service-url: http://localhost:8085/
          health-url: http://localhost:8085/actuator/health
          management-url: http://localhost:8085/actuator

management:
  endpoint:
    health:
      show-details: always

contact:
  confirmation:
    max-attempts: 3
    expiration-seconds: 600
    resend-seconds: 300
