insert into book (title, price, discount) values ('velit eu est congue elementum in', 6784, 0);
insert into book (title, price, discount) values ('consequat metus sapien ut nunc vestibulum', 5757, 45);
insert into book (title, price, discount) values ('leo odio condimentum id luctus nec', 9118, 31);
insert into book (title, price, discount) values ('sed vestibulum sit amet cursus id', 1718, 65);
insert into book (title, price, discount) values ('id ligula suspendisse', 8634, 58);
insert into book (title, price, discount) values ('nulla sed accumsan felis ut at', 4247, 76);
insert into book (title, price, discount) values ('aliquam quis turpis eget elit sodales', 9859, 92);
insert into book (title, price, discount) values ('eleifend quam a odio', 7851, 53);
insert into book (title, price, discount) values ('at velit vivamus vel nulla eget', 6033, 92);
insert into book (title, price, discount) values ('quam sollicitudin vitae consectetuer', 7247, 23);
insert into book (title, price, discount) values ('dolor vel est donec odio justo sollicitudin', 4715, 67);
insert into book (title, price, discount) values ('ut nunc vestibulum ante ipsum primis', 9538, 10);
insert into book (title, price, discount) values ('ultrices posuere cubilia curae', 6998, 99);
insert into book (title, price, discount) values ('nascetur ridiculus mus etiam vel augue', 4621, 12);
insert into book (title, price, discount) values ('pede lobortis ligula sit', 286, 70);
insert into book (title, price, discount) values ('consequat lectus in est risus', 4022, 31);
insert into book (title, price, discount) values ('augue a suscipit nulla elit', 5495, 59);
insert into book (title, price, discount) values ('rutrum at lorem integer tincidunt ante vel', 3554, 58);
insert into book (title, price, discount) values ('ut erat', 8473, 44);
insert into book (title, price, discount) values ('et ultrices posuere cubilia', 3496, 30);
insert into book (title, price, discount) values ('lacinia eget tincidunt eget tempus vel pede', 1881, 64);
insert into book (title, price, discount) values ('amet sem fusce consequat nulla', 8949, 3);
insert into book (title, price, discount) values ('posuere cubilia curae duis faucibus accumsan', 6099, 91);
insert into book (title, price, discount) values ('odio curabitur convallis duis consequat', 3988, 63);
insert into book (title, price, discount) values ('ut suscipit a feugiat', 5973, 41);
insert into book (title, price, discount) values ('dignissim vestibulum vestibulum', 6319, 61);
insert into book (title, price, discount) values ('morbi a ipsum integer a', 5283, 56);
insert into book (title, price, discount) values ('id turpis integer aliquet massa id lobortis', 9711, 40);
insert into book (title, price, discount) values ('vel est donec odio justo sollicitudin ut', 4980, 15);
insert into book (title, price, discount) values ('phasellus in', 7325, 69);
insert into book (title, price, discount) values ('tempor turpis nec euismod scelerisque quam', 622, 62);
insert into book (title, price, discount) values ('arcu libero rutrum ac lobortis', 4837, 68);
insert into book (title, price, discount) values ('integer pede justo lacinia', 1227, 27);
insert into book (title, price, discount) values ('sagittis dui vel nisl duis ac', 3369, 21);
insert into book (title, price, discount) values ('habitasse platea dictumst morbi vestibulum velit', 2053, 14);
insert into book (title, price, discount) values ('sit amet', 1810, 66);
insert into book (title, price, discount) values ('nam nulla', 7780, 12);
insert into book (title, price, discount) values ('ultrices enim lorem ipsum', 4903, 49);
insert into book (title, price, discount) values ('luctus nec molestie sed justo', 5272, 65);
insert into book (title, price, discount) values ('phasellus in felis donec semper sapien a', 3915, 64);
insert into book (title, price, discount) values ('tempor turpis', 7977, 75);
insert into book (title, price, discount) values ('commodo vulputate justo in', 1116, 18);
insert into book (title, price, discount) values ('nonummy integer non velit', 7298, 59);
insert into book (title, price, discount) values ('vitae mattis nibh ligula', 4091, 67);
insert into book (title, price, discount) values ('nonummy integer non velit donec', 4364, 10);
insert into book (title, price, discount) values ('blandit mi in', 1503, 17);
insert into book (title, price, discount) values ('mauris ullamcorper purus', 592, 6);
insert into book (title, price, discount) values ('habitasse platea', 3019, 80);
insert into book (title, price, discount) values ('ligula vehicula consequat morbi', 8942, 37);
insert into book (title, price, discount) values ('habitasse platea dictumst aliquam augue', 1875, 0);
insert into book (title, price, discount) values ('diam id ornare imperdiet sapien urna', 1748, 12);
insert into book (title, price, discount) values ('non ligula pellentesque ultrices phasellus', 2656, 86);
insert into book (title, price, discount) values ('justo maecenas', 1983, 13);
insert into book (title, price, discount) values ('lacus purus', 828, 64);
insert into book (title, price, discount) values ('ornare consequat lectus in est risus', 8322, 57);
insert into book (title, price, discount) values ('erat volutpat in congue etiam', 660, 87);
insert into book (title, price, discount) values ('aliquam erat volutpat', 8637, 73);
insert into book (title, price, discount) values ('faucibus orci luctus', 1967, 65);
insert into book (title, price, discount) values ('nunc viverra dapibus nulla suscipit ligula', 6086, 6);
insert into book (title, price, discount) values ('suscipit ligula in lacus curabitur', 9636, 83);
insert into book (title, price, discount) values ('duis faucibus accumsan odio curabitur convallis duis', 8556, 16);
insert into book (title, price, discount) values ('consequat varius integer ac leo pellentesque', 5173, 79);
insert into book (title, price, discount) values ('odio porttitor id consequat in consequat', 9274, 8);
insert into book (title, price, discount) values ('habitasse platea', 4037, 37);
insert into book (title, price, discount) values ('ut ultrices vel augue vestibulum ante ipsum', 154, 75);
insert into book (title, price, discount) values ('ac consequat metus sapien ut nunc vestibulum', 2337, 38);
insert into book (title, price, discount) values ('morbi non', 3295, 35);
insert into book (title, price, discount) values ('ligula vehicula consequat morbi a', 4790, 64);
insert into book (title, price, discount) values ('semper interdum mauris', 1975, 85);
insert into book (title, price, discount) values ('vulputate ut ultrices vel', 8233, 90);
insert into book (title, price, discount) values ('fusce posuere felis sed lacus morbi sem', 1209, 56);
insert into book (title, price, discount) values ('erat id mauris vulputate elementum', 9450, 73);
insert into book (title, price, discount) values ('ultrices enim lorem ipsum dolor sit', 2487, 39);
insert into book (title, price, discount) values ('rhoncus aliquet pulvinar sed nisl', 9524, 73);
insert into book (title, price, discount) values ('dolor quis odio consequat varius', 6903, 76);
insert into book (title, price, discount) values ('eget eros elementum', 3515, 10);
insert into book (title, price, discount) values ('nulla mollis molestie lorem', 907, 78);
insert into book (title, price, discount) values ('a pede posuere nonummy integer', 5280, 76);
insert into book (title, price, discount) values ('diam cras pellentesque volutpat', 2334, 61);
insert into book (title, price, discount) values ('nisl duis ac nibh fusce', 9306, 77);
insert into book (title, price, discount) values ('a ipsum integer a nibh in', 3757, 16);
insert into book (title, price, discount) values ('nulla tellus', 1644, 73);
insert into book (title, price, discount) values ('placerat praesent blandit', 6292, 90);
insert into book (title, price, discount) values ('dui luctus rutrum nulla', 8072, 89);
insert into book (title, price, discount) values ('nisi eu orci mauris lacinia sapien', 4345, 71);
insert into book (title, price, discount) values ('ut mauris eget massa tempor convallis nulla', 8908, 55);
insert into book (title, price, discount) values ('magna bibendum imperdiet', 6874, 7);
insert into book (title, price, discount) values ('amet lobortis sapien sapien', 3695, 82);
insert into book (title, price, discount) values ('justo lacinia', 4539, 55);
insert into book (title, price, discount) values ('mauris non ligula pellentesque ultrices', 8335, 24);
insert into book (title, price, discount) values ('penatibus et magnis dis parturient montes nascetur', 3397, 34);
insert into book (title, price, discount) values ('auctor sed tristique in tempus sit amet', 2184, 46);
insert into book (title, price, discount) values ('amet justo', 7821, 63);
insert into book (title, price, discount) values ('vivamus vestibulum sagittis sapien cum sociis', 7261, 96);
insert into book (title, price, discount) values ('nunc vestibulum ante ipsum', 2302, 69);
insert into book (title, price, discount) values ('ipsum integer a nibh in', 5580, 1);
insert into book (title, price, discount) values ('tristique est', 919, 76);
insert into book (title, price, discount) values ('tincidunt nulla mollis molestie lorem quisque ut', 1134, 84);
insert into book (title, price, discount) values ('id justo sit', 2755, 92);
insert into book (title, price, discount) values ('quis turpis sed', 8578, 55);
insert into book (title, price, discount) values ('pede ullamcorper', 7230, 73);
insert into book (title, price, discount) values ('id nulla ultrices aliquet', 7445, 38);
insert into book (title, price, discount) values ('nascetur ridiculus', 9538, 26);
insert into book (title, price, discount) values ('vulputate luctus cum sociis natoque penatibus', 7157, 49);
insert into book (title, price, discount) values ('etiam pretium iaculis justo in hac', 2469, 74);
insert into book (title, price, discount) values ('quam fringilla rhoncus mauris enim leo', 8943, 87);
insert into book (title, price, discount) values ('interdum mauris ullamcorper purus sit', 31, 45);
insert into book (title, price, discount) values ('sapien varius ut blandit', 9487, 28);
insert into book (title, price, discount) values ('felis sed interdum venenatis turpis', 1941, 49);
insert into book (title, price, discount) values ('suspendisse accumsan tortor quis', 412, 81);
insert into book (title, price, discount) values ('nulla ultrices', 4754, 1);
insert into book (title, price, discount) values ('ut dolor morbi vel lectus in quam', 5926, 12);
insert into book (title, price, discount) values ('rhoncus mauris enim leo', 3708, 58);
insert into book (title, price, discount) values ('orci luctus et ultrices posuere', 1477, 61);
insert into book (title, price, discount) values ('feugiat et eros', 4345, 67);
insert into book (title, price, discount) values ('sapien dignissim vestibulum vestibulum ante ipsum primis', 5321, 20);
insert into book (title, price, discount) values ('porttitor lorem id ligula suspendisse ornare consequat', 9908, 69);
insert into book (title, price, discount) values ('leo pellentesque ultrices', 4938, 44);
insert into book (title, price, discount) values ('aliquam non mauris morbi non', 2245, 47);
insert into book (title, price, discount) values ('nisi volutpat eleifend donec ut dolor', 4074, 89);
insert into book (title, price, discount) values ('sit amet justo morbi ut odio cras', 7749, 59);
insert into book (title, price, discount) values ('sit amet nunc viverra', 1527, 25);
insert into book (title, price, discount) values ('id lobortis convallis tortor', 3611, 3);
insert into book (title, price, discount) values ('ultrices erat', 9311, 69);
insert into book (title, price, discount) values ('massa donec dapibus duis at', 6754, 19);
insert into book (title, price, discount) values ('luctus et ultrices posuere cubilia curae mauris', 5129, 38);
insert into book (title, price, discount) values ('volutpat in', 4027, 11);
insert into book (title, price, discount) values ('ut massa volutpat convallis morbi odio', 6969, 39);
insert into book (title, price, discount) values ('nec euismod scelerisque quam turpis adipiscing', 1030, 3);
insert into book (title, price, discount) values ('ante vestibulum ante ipsum', 457, 35);
insert into book (title, price, discount) values ('id massa id nisl venenatis', 1121, 13);
insert into book (title, price, discount) values ('erat curabitur gravida nisi at', 9626, 42);
insert into book (title, price, discount) values ('nulla suspendisse potenti', 5762, 86);
insert into book (title, price, discount) values ('lectus suspendisse potenti in', 2135, 47);
insert into book (title, price, discount) values ('imperdiet sapien urna pretium nisl ut volutpat', 435, 11);
insert into book (title, price, discount) values ('lacus morbi sem mauris laoreet ut', 5260, 16);
insert into book (title, price, discount) values ('dictumst aliquam augue quam', 6967, 33);
insert into book (title, price, discount) values ('posuere cubilia curae', 5503, 5);
insert into book (title, price, discount) values ('sodales sed tincidunt eu felis fusce posuere', 1293, 22);
insert into book (title, price, discount) values ('maecenas pulvinar lobortis est phasellus sit amet', 8898, 84);
insert into book (title, price, discount) values ('tortor risus dapibus augue vel accumsan tellus', 4620, 72);
insert into book (title, price, discount) values ('dis parturient montes', 7547, 16);
insert into book (title, price, discount) values ('quisque erat eros viverra eget congue', 301, 23);
insert into book (title, price, discount) values ('in faucibus orci luctus et', 1119, 0);
insert into book (title, price, discount) values ('vel pede morbi porttitor lorem', 1481, 7);
insert into book (title, price, discount) values ('tristique fusce congue', 8094, 80);
insert into book (title, price, discount) values ('enim blandit mi', 8901, 53);
insert into book (title, price, discount) values ('orci luctus et', 7285, 91);
insert into book (title, price, discount) values ('molestie hendrerit at', 4001, 14);
insert into book (title, price, discount) values ('sit amet diam', 645, 1);
insert into book (title, price, discount) values ('neque libero convallis eget eleifend luctus ultricies', 5922, 51);
insert into book (title, price, discount) values ('bibendum imperdiet nullam orci pede', 3721, 73);
insert into book (title, price, discount) values ('pede libero quis orci nullam', 6349, 70);
insert into book (title, price, discount) values ('morbi sem mauris', 569, 32);
insert into book (title, price, discount) values ('diam nam tristique tortor', 1903, 8);
insert into book (title, price, discount) values ('quisque ut erat', 9600, 63);
insert into book (title, price, discount) values ('odio justo sollicitudin ut suscipit', 1226, 33);
insert into book (title, price, discount) values ('ante ipsum', 9463, 50);
insert into book (title, price, discount) values ('suspendisse potenti cras', 8986, 69);
insert into book (title, price, discount) values ('condimentum curabitur in libero ut massa volutpat', 251, 61);
insert into book (title, price, discount) values ('consequat varius integer ac leo pellentesque', 8146, 19);
insert into book (title, price, discount) values ('nulla integer pede justo', 9435, 80);
insert into book (title, price, discount) values ('interdum in ante vestibulum ante ipsum primis', 4716, 82);
insert into book (title, price, discount) values ('sed tristique in tempus sit amet sem', 4071, 62);
insert into book (title, price, discount) values ('nullam molestie nibh in', 9624, 13);
insert into book (title, price, discount) values ('sit amet erat nulla tempus vivamus', 4568, 35);
insert into book (title, price, discount) values ('risus auctor sed tristique', 7513, 73);
insert into book (title, price, discount) values ('libero ut', 548, 65);
insert into book (title, price, discount) values ('nibh quisque id justo sit', 8812, 17);
insert into book (title, price, discount) values ('molestie nibh', 9343, 53);
insert into book (title, price, discount) values ('nunc proin at turpis a', 6430, 61);
insert into book (title, price, discount) values ('viverra pede ac diam', 8029, 6);
insert into book (title, price, discount) values ('nulla suspendisse potenti cras', 5410, 37);
insert into book (title, price, discount) values ('in faucibus orci luctus et', 7115, 51);
insert into book (title, price, discount) values ('non velit nec nisi', 5592, 64);
insert into book (title, price, discount) values ('at velit vivamus vel', 2193, 21);
insert into book (title, price, discount) values ('at vulputate vitae nisl aenean', 7011, 12);
insert into book (title, price, discount) values ('donec pharetra magna vestibulum aliquet ultrices erat', 2254, 55);
insert into book (title, price, discount) values ('sagittis sapien cum', 2886, 50);
insert into book (title, price, discount) values ('nulla suscipit ligula in', 245, 87);
insert into book (title, price, discount) values ('nec nisi', 1178, 53);
insert into book (title, price, discount) values ('purus aliquet at feugiat non', 1146, 97);
insert into book (title, price, discount) values ('odio cras mi', 1685, 59);
insert into book (title, price, discount) values ('a suscipit nulla elit', 783, 75);
insert into book (title, price, discount) values ('nulla dapibus dolor vel est', 548, 42);
insert into book (title, price, discount) values ('ullamcorper augue a suscipit nulla elit', 6671, 43);
insert into book (title, price, discount) values ('metus aenean fermentum donec ut mauris', 1924, 28);
insert into book (title, price, discount) values ('sapien dignissim vestibulum', 977, 11);
insert into book (title, price, discount) values ('sit amet turpis elementum ligula vehicula consequat', 7961, 83);
insert into book (title, price, discount) values ('platea dictumst etiam faucibus cursus', 4594, 69);
insert into book (title, price, discount) values ('non ligula pellentesque', 250, 37);
insert into book (title, price, discount) values ('arcu sed', 2533, 99);
insert into book (title, price, discount) values ('bibendum morbi non quam nec dui', 9898, 66);
insert into book (title, price, discount) values ('donec ut dolor', 5319, 58);
insert into book (title, price, discount) values ('vestibulum ac est lacinia nisi venenatis', 6748, 12);
insert into book (title, price, discount) values ('aenean lectus pellentesque eget nunc', 1069, 15);
insert into book (title, price, discount) values ('pellentesque ultrices mattis', 4508, 95);
insert into book (title, price, discount) values ('cubilia curae mauris viverra diam vitae quam', 1753, 58);
insert into book (title, price, discount) values ('erat tortor sollicitudin mi sit', 7704, 77);
insert into book (title, price, discount) values ('lobortis vel dapibus at diam nam tristique', 5962, 7);
insert into book (title, price, discount) values ('sagittis sapien cum sociis natoque penatibus', 742, 76);
insert into book (title, price, discount) values ('vestibulum ac est lacinia nisi venenatis', 5771, 81);
insert into book (title, price, discount) values ('sit amet eros suspendisse accumsan', 9560, 75);
insert into book (title, price, discount) values ('tempor convallis nulla', 7045, 6);
insert into book (title, price, discount) values ('quam pharetra magna ac consequat metus sapien', 3768, 87);
insert into book (title, price, discount) values ('sapien a libero', 241, 91);
insert into book (title, price, discount) values ('orci luctus et ultrices posuere', 915, 90);
insert into book (title, price, discount) values ('in ante vestibulum ante ipsum', 1949, 22);
insert into book (title, price, discount) values ('nascetur ridiculus mus vivamus vestibulum sagittis', 6796, 95);
insert into book (title, price, discount) values ('ac leo pellentesque ultrices mattis odio donec', 3538, 20);
insert into book (title, price, discount) values ('aenean fermentum', 3976, 41);
insert into book (title, price, discount) values ('pede ullamcorper augue a suscipit', 6314, 8);
insert into book (title, price, discount) values ('in blandit ultrices enim', 6282, 68);
insert into book (title, price, discount) values ('aliquet pulvinar', 3715, 64);
insert into book (title, price, discount) values ('sit amet eros suspendisse', 4917, 91);
insert into book (title, price, discount) values ('in hac habitasse platea dictumst morbi', 5175, 15);
insert into book (title, price, discount) values ('nulla nisl nunc', 8294, 42);
insert into book (title, price, discount) values ('ante ipsum primis in faucibus orci', 2956, 73);
insert into book (title, price, discount) values ('urna ut tellus nulla ut erat', 2946, 50);
insert into book (title, price, discount) values ('quis libero nullam', 3955, 65);
insert into book (title, price, discount) values ('hac habitasse platea dictumst etiam', 2966, 74);
insert into book (title, price, discount) values ('nulla dapibus', 5076, 4);
insert into book (title, price, discount) values ('semper rutrum nulla nunc purus', 5583, 24);
insert into book (title, price, discount) values ('ultrices posuere cubilia curae nulla dapibus', 4430, 82);
insert into book (title, price, discount) values ('dapibus nulla suscipit ligula in', 586, 95);
insert into book (title, price, discount) values ('dictumst aliquam', 4488, 9);
insert into book (title, price, discount) values ('varius integer ac leo pellentesque ultrices', 9959, 61);
insert into book (title, price, discount) values ('phasellus in felis donec', 403, 31);
insert into book (title, price, discount) values ('quis tortor id', 5492, 48);
insert into book (title, price, discount) values ('turpis a pede posuere nonummy integer', 2804, 56);
insert into book (title, price, discount) values ('nam congue', 9814, 97);
insert into book (title, price, discount) values ('at velit eu est congue', 5726, 16);
insert into book (title, price, discount) values ('sapien in sapien iaculis congue vivamus metus', 6586, 4);
insert into book (title, price, discount) values ('est risus', 5914, 52);
insert into book (title, price, discount) values ('viverra pede', 7796, 9);
insert into book (title, price, discount) values ('morbi odio odio elementum eu interdum eu', 3272, 11);
insert into book (title, price, discount) values ('sapien iaculis congue vivamus metus arcu adipiscing', 8528, 67);
insert into book (title, price, discount) values ('hac habitasse platea dictumst', 3543, 29);
insert into book (title, price, discount) values ('sed lacus morbi sem mauris laoreet', 8043, 22);
insert into book (title, price, discount) values ('tortor quis', 7196, 94);
insert into book (title, price, discount) values ('vulputate elementum', 1653, 88);
insert into book (title, price, discount) values ('id ornare imperdiet sapien urna pretium', 2231, 42);
insert into book (title, price, discount) values ('at feugiat', 5030, 81);
insert into book (title, price, discount) values ('nunc nisl duis bibendum', 7744, 66);
insert into book (title, price, discount) values ('dui luctus rutrum nulla tellus in sagittis', 6356, 88);
insert into book (title, price, discount) values ('lorem quisque ut', 7840, 26);
insert into book (title, price, discount) values ('dolor quis odio consequat', 7244, 99);
insert into book (title, price, discount) values ('nonummy maecenas tincidunt lacus', 2663, 70);
insert into book (title, price, discount) values ('id nisl venenatis', 7618, 54);
insert into book (title, price, discount) values ('curae duis faucibus accumsan', 3874, 85);
insert into book (title, price, discount) values ('posuere nonummy integer non velit donec', 1765, 46);
insert into book (title, price, discount) values ('sed ante vivamus tortor duis mattis', 2485, 3);
insert into book (title, price, discount) values ('eleifend luctus ultricies eu nibh quisque id', 8490, 45);
insert into book (title, price, discount) values ('mauris laoreet ut rhoncus aliquet pulvinar', 4089, 34);
insert into book (title, price, discount) values ('nulla sed accumsan felis ut at', 9220, 57);
insert into book (title, price, discount) values ('mauris enim leo rhoncus sed vestibulum', 5399, 33);
insert into book (title, price, discount) values ('dolor quis odio consequat varius integer', 7044, 47);
insert into book (title, price, discount) values ('sapien urna pretium nisl', 9314, 54);
insert into book (title, price, discount) values ('eget eleifend luctus ultricies eu nibh', 8717, 16);
insert into book (title, price, discount) values ('ante ipsum', 281, 99);
insert into book (title, price, discount) values ('eu est congue elementum in hac', 5864, 98);
insert into book (title, price, discount) values ('sagittis sapien', 9122, 7);
insert into book (title, price, discount) values ('augue luctus tincidunt nulla mollis molestie', 7631, 28);
insert into book (title, price, discount) values ('aenean lectus pellentesque eget nunc', 2798, 89);
insert into book (title, price, discount) values ('convallis nunc proin at turpis', 9736, 55);
insert into book (title, price, discount) values ('integer ac neque duis', 5855, 57);
insert into book (title, price, discount) values ('blandit nam nulla', 1372, 59);
insert into book (title, price, discount) values ('rhoncus sed vestibulum sit amet cursus', 8127, 26);
insert into book (title, price, discount) values ('porttitor pede justo eu massa', 6117, 35);
insert into book (title, price, discount) values ('cras pellentesque volutpat dui maecenas tristique', 3149, 45);
insert into book (title, price, discount) values ('justo in blandit ultrices enim lorem ipsum', 9442, 26);
insert into book (title, price, discount) values ('faucibus orci luctus et', 9420, 44);
insert into book (title, price, discount) values ('ante ipsum primis in faucibus', 9503, 7);
insert into book (title, price, discount) values ('luctus rutrum nulla', 6374, 1);
insert into book (title, price, discount) values ('pretium iaculis diam', 4292, 23);
insert into book (title, price, discount) values ('ipsum praesent blandit lacinia erat', 2779, 99);
insert into book (title, price, discount) values ('vel nulla eget', 9054, 68);
insert into book (title, price, discount) values ('congue vivamus metus', 9172, 80);
insert into book (title, price, discount) values ('tincidunt ante vel ipsum', 6253, 0);
insert into book (title, price, discount) values ('convallis tortor', 4239, 88);
insert into book (title, price, discount) values ('pretium iaculis diam', 9286, 8);
insert into book (title, price, discount) values ('tincidunt lacus', 4837, 97);
insert into book (title, price, discount) values ('nisi at', 3653, 48);
insert into book (title, price, discount) values ('eu tincidunt in leo maecenas', 829, 22);
insert into book (title, price, discount) values ('ut volutpat sapien arcu sed augue aliquam', 5159, 55);
insert into book (title, price, discount) values ('at feugiat non pretium quis', 9247, 86);
insert into book (title, price, discount) values ('massa id lobortis convallis tortor risus', 1342, 61);
insert into book (title, price, discount) values ('at velit vivamus', 6449, 63);
insert into book (title, price, discount) values ('molestie nibh in lectus pellentesque at', 6689, 31);
insert into book (title, price, discount) values ('varius integer ac', 8000, 10);
insert into book (title, price, discount) values ('vivamus vel nulla eget eros', 4063, 72);
insert into book (title, price, discount) values ('blandit nam', 722, 11);
insert into book (title, price, discount) values ('rutrum nulla tellus in sagittis dui vel', 5731, 40);
insert into book (title, price, discount) values ('aliquet massa id lobortis convallis tortor risus', 6819, 87);
insert into book (title, price, discount) values ('quam turpis adipiscing lorem', 6400, 90);
insert into book (title, price, discount) values ('vitae nisl aenean lectus', 8957, 27);
insert into book (title, price, discount) values ('amet justo morbi ut odio cras', 2729, 94);
insert into book (title, price, discount) values ('sapien iaculis congue vivamus metus arcu', 1112, 38);
insert into book (title, price, discount) values ('semper rutrum', 6622, 25);
insert into book (title, price, discount) values ('eu nibh quisque id justo', 4408, 53);
insert into book (title, price, discount) values ('quam a odio in hac', 8991, 91);
insert into book (title, price, discount) values ('magna bibendum imperdiet nullam', 2862, 91);
insert into book (title, price, discount) values ('mus vivamus vestibulum', 7878, 40);
insert into book (title, price, discount) values ('volutpat erat quisque erat', 7680, 6);
insert into book (title, price, discount) values ('consectetuer eget rutrum at lorem integer', 887, 35);
insert into book (title, price, discount) values ('pede justo eu massa donec dapibus', 1671, 74);
insert into book (title, price, discount) values ('tincidunt ante vel ipsum praesent', 8415, 60);
insert into book (title, price, discount) values ('a pede', 674, 97);
insert into book (title, price, discount) values ('luctus et ultrices posuere cubilia', 2196, 62);
insert into book (title, price, discount) values ('tempus semper est quam pharetra magna', 6693, 57);
insert into book (title, price, discount) values ('mattis nibh ligula nec', 2336, 93);
insert into book (title, price, discount) values ('nulla tellus in', 6309, 93);
insert into book (title, price, discount) values ('vitae nisl aenean lectus pellentesque eget nunc', 3591, 78);
insert into book (title, price, discount) values ('cras in purus eu magna vulputate', 3750, 6);
insert into book (title, price, discount) values ('sapien varius ut blandit non interdum in', 7546, 38);
insert into book (title, price, discount) values ('ultrices vel augue vestibulum ante ipsum primis', 7739, 22);
insert into book (title, price, discount) values ('luctus tincidunt nulla mollis', 645, 66);
insert into book (title, price, discount) values ('sodales sed tincidunt eu', 6228, 59);
insert into book (title, price, discount) values ('massa id nisl', 9098, 97);
insert into book (title, price, discount) values ('ligula sit amet eleifend', 7116, 75);
insert into book (title, price, discount) values ('vestibulum eget vulputate ut', 986, 4);
insert into book (title, price, discount) values ('cubilia curae mauris viverra diam', 8763, 26);
insert into book (title, price, discount) values ('dui maecenas tristique est et', 2394, 62);
insert into book (title, price, discount) values ('eget semper', 2504, 88);
insert into book (title, price, discount) values ('lacinia eget tincidunt eget', 3170, 79);
insert into book (title, price, discount) values ('enim sit amet nunc viverra', 5093, 8);
insert into book (title, price, discount) values ('luctus cum sociis natoque penatibus', 9656, 58);
insert into book (title, price, discount) values ('magna at nunc', 8306, 79);
insert into book (title, price, discount) values ('eget congue eget semper rutrum', 6570, 73);
insert into book (title, price, discount) values ('ante ipsum', 7720, 42);
insert into book (title, price, discount) values ('sociis natoque penatibus', 9245, 14);
insert into book (title, price, discount) values ('sollicitudin mi sit amet', 2668, 77);
insert into book (title, price, discount) values ('at dolor quis odio consequat', 4633, 32);
insert into book (title, price, discount) values ('sed sagittis nam', 5914, 45);
insert into book (title, price, discount) values ('odio porttitor id consequat in consequat', 569, 28);
insert into book (title, price, discount) values ('nulla elit ac nulla sed vel', 9756, 19);
insert into book (title, price, discount) values ('nunc vestibulum', 5198, 92);
insert into book (title, price, discount) values ('sapien in sapien iaculis congue vivamus', 4458, 74);
insert into book (title, price, discount) values ('dapibus duis at velit eu est congue', 2205, 45);
insert into book (title, price, discount) values ('semper rutrum nulla nunc purus', 7791, 81);
insert into book (title, price, discount) values ('lobortis vel dapibus at diam nam tristique', 8749, 79);
insert into book (title, price, discount) values ('interdum mauris', 3733, 7);
insert into book (title, price, discount) values ('pretium quis lectus suspendisse potenti', 1219, 59);
insert into book (title, price, discount) values ('a libero nam', 5074, 61);
insert into book (title, price, discount) values ('nulla pede ullamcorper augue', 3862, 18);
insert into book (title, price, discount) values ('justo morbi ut odio cras', 1301, 98);
insert into book (title, price, discount) values ('malesuada in imperdiet et commodo vulputate justo', 8403, 44);
insert into book (title, price, discount) values ('posuere nonummy integer non velit donec', 2419, 89);
insert into book (title, price, discount) values ('quis tortor id nulla ultrices', 3239, 65);
insert into book (title, price, discount) values ('amet erat nulla tempus vivamus in', 9001, 53);
insert into book (title, price, discount) values ('potenti nullam', 3867, 31);
insert into book (title, price, discount) values ('pede justo eu massa donec dapibus duis', 8133, 77);
insert into book (title, price, discount) values ('ac est lacinia nisi venenatis tristique', 4454, 12);
insert into book (title, price, discount) values ('quam pede lobortis ligula sit amet', 2545, 61);
insert into book (title, price, discount) values ('in sapien iaculis', 8978, 46);
insert into book (title, price, discount) values ('sed magna at', 1328, 28);
insert into book (title, price, discount) values ('non ligula pellentesque ultrices phasellus id', 5746, 10);
insert into book (title, price, discount) values ('vestibulum eget vulputate ut ultrices vel', 49, 86);
insert into book (title, price, discount) values ('nisi venenatis tristique', 6304, 98);
insert into book (title, price, discount) values ('ac enim in tempor', 1273, 5);
insert into book (title, price, discount) values ('cubilia curae donec', 7107, 5);
insert into book (title, price, discount) values ('at diam', 4773, 90);
insert into book (title, price, discount) values ('orci luctus et ultrices', 5227, 99);
insert into book (title, price, discount) values ('ullamcorper augue a suscipit nulla elit ac', 7434, 34);
insert into book (title, price, discount) values ('mauris enim', 2766, 2);
insert into book (title, price, discount) values ('pellentesque volutpat', 1958, 74);
insert into book (title, price, discount) values ('malesuada in imperdiet et commodo', 3107, 77);
insert into book (title, price, discount) values ('mi in', 4697, 54);
insert into book (title, price, discount) values ('nulla facilisi cras non', 9337, 77);
insert into book (title, price, discount) values ('nulla quisque arcu', 8026, 9);
insert into book (title, price, discount) values ('diam in magna bibendum', 8370, 46);
insert into book (title, price, discount) values ('lectus suspendisse potenti in', 9242, 84);
insert into book (title, price, discount) values ('tempor convallis nulla', 9655, 75);
insert into book (title, price, discount) values ('sit amet', 4652, 93);
insert into book (title, price, discount) values ('massa tempor convallis nulla neque libero', 526, 80);
insert into book (title, price, discount) values ('lobortis convallis tortor risus dapibus', 5828, 42);
insert into book (title, price, discount) values ('ante nulla justo aliquam quis turpis eget', 3115, 58);
insert into book (title, price, discount) values ('mus vivamus vestibulum', 6702, 86);
insert into book (title, price, discount) values ('tortor quis', 580, 30);
insert into book (title, price, discount) values ('tempor convallis nulla', 7241, 46);
insert into book (title, price, discount) values ('ultrices vel augue vestibulum ante ipsum', 9070, 23);
insert into book (title, price, discount) values ('interdum mauris ullamcorper', 7398, 22);
insert into book (title, price, discount) values ('potenti nullam', 1724, 10);
insert into book (title, price, discount) values ('sit amet justo morbi ut odio cras', 9965, 73);
insert into book (title, price, discount) values ('donec quis orci eget orci vehicula condimentum', 9084, 10);
insert into book (title, price, discount) values ('molestie lorem quisque ut erat curabitur', 6987, 93);
insert into book (title, price, discount) values ('eu sapien cursus vestibulum proin eu mi', 2597, 8);
insert into book (title, price, discount) values ('nullam porttitor lacus at', 2516, 63);
insert into book (title, price, discount) values ('nulla nunc purus phasellus in', 5795, 26);
insert into book (title, price, discount) values ('sit amet cursus id turpis integer aliquet', 9752, 18);
insert into book (title, price, discount) values ('mauris enim leo rhoncus sed', 4273, 46);
insert into book (title, price, discount) values ('parturient montes nascetur ridiculus', 2386, 63);
insert into book (title, price, discount) values ('leo pellentesque ultrices mattis', 7022, 30);
insert into book (title, price, discount) values ('fusce consequat nulla nisl', 2490, 48);
insert into book (title, price, discount) values ('est risus auctor sed', 4660, 15);
insert into book (title, price, discount) values ('pharetra magna vestibulum aliquet ultrices erat', 1770, 64);
insert into book (title, price, discount) values ('elit proin', 6929, 99);
insert into book (title, price, discount) values ('sit amet sapien', 4487, 67);
insert into book (title, price, discount) values ('eu felis fusce posuere felis', 9396, 35);
insert into book (title, price, discount) values ('vivamus metus arcu adipiscing molestie', 6514, 22);
insert into book (title, price, discount) values ('odio consequat varius integer', 4425, 23);
insert into book (title, price, discount) values ('erat vestibulum sed', 819, 32);
insert into book (title, price, discount) values ('scelerisque quam turpis adipiscing lorem vitae mattis', 6972, 56);
insert into book (title, price, discount) values ('odio condimentum id', 3286, 28);
insert into book (title, price, discount) values ('parturient montes nascetur ridiculus mus', 4682, 90);
insert into book (title, price, discount) values ('in quam fringilla rhoncus', 8868, 42);
insert into book (title, price, discount) values ('pellentesque viverra pede ac', 3147, 14);
insert into book (title, price, discount) values ('quis orci eget orci vehicula condimentum', 2624, 55);
insert into book (title, price, discount) values ('felis sed interdum venenatis turpis enim blandit', 604, 5);
insert into book (title, price, discount) values ('pede justo', 6036, 92);
insert into book (title, price, discount) values ('nam nulla integer', 9801, 98);
insert into book (title, price, discount) values ('tincidunt eget tempus vel pede morbi porttitor', 6605, 25);
insert into book (title, price, discount) values ('odio odio elementum eu interdum eu', 5652, 6);
insert into book (title, price, discount) values ('turpis a', 6470, 82);
insert into book (title, price, discount) values ('dui maecenas tristique', 7378, 88);
insert into book (title, price, discount) values ('nulla ut', 8030, 71);
insert into book (title, price, discount) values ('pretium iaculis', 5059, 28);
insert into book (title, price, discount) values ('vestibulum ac est', 6146, 74);
insert into book (title, price, discount) values ('luctus cum', 8732, 74);
insert into book (title, price, discount) values ('ultrices phasellus id sapien in sapien', 7170, 27);
insert into book (title, price, discount) values ('ridiculus mus vivamus vestibulum sagittis sapien cum', 5561, 5);
insert into book (title, price, discount) values ('et ultrices posuere cubilia curae nulla dapibus', 8884, 39);
insert into book (title, price, discount) values ('vitae ipsum aliquam non mauris morbi', 2668, 66);
insert into book (title, price, discount) values ('mus etiam vel', 5364, 25);
insert into book (title, price, discount) values ('nonummy maecenas tincidunt lacus at velit vivamus', 2081, 93);
insert into book (title, price, discount) values ('ligula suspendisse ornare consequat', 9893, 62);
insert into book (title, price, discount) values ('vitae quam suspendisse', 5488, 48);
insert into book (title, price, discount) values ('non lectus aliquam sit amet', 3195, 65);
insert into book (title, price, discount) values ('amet consectetuer adipiscing elit proin', 5458, 96);
insert into book (title, price, discount) values ('dapibus augue vel accumsan tellus', 2438, 20);
insert into book (title, price, discount) values ('donec quis orci', 9593, 83);
insert into book (title, price, discount) values ('eros suspendisse accumsan tortor quis turpis', 5829, 43);
insert into book (title, price, discount) values ('in faucibus', 2582, 0);
insert into book (title, price, discount) values ('turpis donec', 3681, 47);
insert into book (title, price, discount) values ('vestibulum sit amet cursus id turpis', 9387, 18);
insert into book (title, price, discount) values ('dignissim vestibulum', 8019, 72);
insert into book (title, price, discount) values ('hac habitasse platea dictumst aliquam', 3911, 60);
insert into book (title, price, discount) values ('lacus morbi quis tortor id', 4835, 25);
insert into book (title, price, discount) values ('arcu sed augue aliquam erat volutpat in', 3236, 33);
insert into book (title, price, discount) values ('interdum mauris ullamcorper', 2692, 30);
insert into book (title, price, discount) values ('justo sollicitudin ut suscipit a feugiat', 874, 73);
insert into book (title, price, discount) values ('platea dictumst maecenas ut massa quis augue', 942, 47);
insert into book (title, price, discount) values ('porttitor lorem id ligula suspendisse ornare consequat', 3599, 26);
insert into book (title, price, discount) values ('in tempus sit', 1226, 49);
insert into book (title, price, discount) values ('sit amet', 5016, 57);
insert into book (title, price, discount) values ('viverra dapibus nulla', 8169, 75);
insert into book (title, price, discount) values ('erat nulla tempus', 3678, 40);
insert into book (title, price, discount) values ('odio odio elementum eu interdum', 9486, 5);
insert into book (title, price, discount) values ('morbi porttitor', 3793, 37);
insert into book (title, price, discount) values ('lacus purus aliquet at feugiat non', 1553, 53);
insert into book (title, price, discount) values ('ac consequat', 6448, 92);
insert into book (title, price, discount) values ('quis turpis sed ante vivamus tortor duis', 9085, 41);
insert into book (title, price, discount) values ('aliquet at feugiat', 6861, 61);
insert into book (title, price, discount) values ('tortor quis', 2772, 6);
insert into book (title, price, discount) values ('interdum in', 9318, 8);
insert into book (title, price, discount) values ('cubilia curae mauris viverra', 300, 54);
insert into book (title, price, discount) values ('nascetur ridiculus mus vivamus vestibulum sagittis sapien', 2560, 44);
insert into book (title, price, discount) values ('pellentesque ultrices phasellus id', 9991, 26);
insert into book (title, price, discount) values ('integer tincidunt ante vel ipsum', 8678, 34);
insert into book (title, price, discount) values ('dictumst morbi', 261, 32);
insert into book (title, price, discount) values ('aliquam augue quam sollicitudin vitae', 6010, 34);
insert into book (title, price, discount) values ('lorem ipsum', 7000, 56);
insert into book (title, price, discount) values ('enim sit', 8918, 34);
insert into book (title, price, discount) values ('quis justo maecenas rhoncus aliquam', 6526, 38);
insert into book (title, price, discount) values ('ullamcorper augue a suscipit nulla', 7270, 61);
insert into book (title, price, discount) values ('pede ac diam cras pellentesque', 6544, 51);
insert into book (title, price, discount) values ('bibendum felis sed interdum venenatis', 5320, 32);
insert into book (title, price, discount) values ('sapien arcu sed augue', 7191, 94);
insert into book (title, price, discount) values ('natoque penatibus et magnis', 5642, 97);
insert into book (title, price, discount) values ('leo odio condimentum id luctus nec', 8327, 40);
insert into book (title, price, discount) values ('magna ac consequat metus sapien ut nunc', 9086, 91);
insert into book (title, price, discount) values ('integer pede justo lacinia eget tincidunt eget', 3745, 74);
insert into book (title, price, discount) values ('quis justo maecenas rhoncus', 8250, 17);
insert into book (title, price, discount) values ('imperdiet nullam orci pede venenatis non', 2659, 90);
insert into book (title, price, discount) values ('iaculis diam erat fermentum justo nec condimentum', 3419, 41);
insert into book (title, price, discount) values ('rutrum rutrum neque aenean auctor gravida', 8446, 58);
insert into book (title, price, discount) values ('quam nec dui luctus rutrum', 6580, 67);
insert into book (title, price, discount) values ('natoque penatibus', 7739, 52);
insert into book (title, price, discount) values ('vel nisl duis ac nibh fusce', 8874, 65);
insert into book (title, price, discount) values ('ultrices libero non mattis pulvinar nulla pede', 2544, 95);
insert into book (title, price, discount) values ('vestibulum ante ipsum primis', 9337, 79);
insert into book (title, price, discount) values ('justo maecenas', 5260, 56);
insert into book (title, price, discount) values ('nascetur ridiculus mus etiam vel augue vestibulum', 3390, 18);
insert into book (title, price, discount) values ('et tempus semper est quam pharetra', 8506, 11);
insert into book (title, price, discount) values ('sapien arcu sed', 9640, 3);
insert into book (title, price, discount) values ('at lorem integer', 3251, 25);
insert into book (title, price, discount) values ('quis turpis sed ante vivamus tortor duis', 8174, 69);
insert into book (title, price, discount) values ('integer aliquet massa id lobortis convallis tortor', 6995, 26);
insert into book (title, price, discount) values ('diam id', 3525, 17);
insert into book (title, price, discount) values ('id turpis integer aliquet massa', 1564, 11);
insert into book (title, price, discount) values ('lectus suspendisse potenti in eleifend quam', 2925, 62);
insert into book (title, price, discount) values ('primis in faucibus orci', 5418, 20);
insert into book (title, price, discount) values ('est phasellus sit amet erat nulla', 1994, 31);
insert into book (title, price, discount) values ('amet nulla quisque arcu libero rutrum', 6842, 28);
insert into book (title, price, discount) values ('consequat dui', 1845, 63);
insert into book (title, price, discount) values ('sed nisl nunc rhoncus dui vel', 3730, 72);
insert into book (title, price, discount) values ('ut mauris eget massa tempor convallis nulla', 8474, 84);
insert into book (title, price, discount) values ('pede venenatis non sodales sed tincidunt eu', 3050, 71);
insert into book (title, price, discount) values ('sed augue aliquam erat volutpat in congue', 3083, 72);
insert into book (title, price, discount) values ('mollis molestie lorem', 8846, 4);
insert into book (title, price, discount) values ('rutrum nulla tellus', 4983, 98);
insert into book (title, price, discount) values ('donec ut dolor morbi vel', 9988, 49);
insert into book (title, price, discount) values ('vestibulum quam sapien varius ut', 3899, 40);
insert into book (title, price, discount) values ('luctus et', 4031, 15);
insert into book (title, price, discount) values ('nec nisi vulputate', 3246, 38);
insert into book (title, price, discount) values ('nulla facilisi', 8594, 44);
insert into book (title, price, discount) values ('amet consectetuer adipiscing elit proin risus', 5728, 27);
insert into book (title, price, discount) values ('ornare imperdiet', 3213, 98);
insert into book (title, price, discount) values ('rutrum nulla tellus in sagittis', 7542, 1);
insert into book (title, price, discount) values ('eu magna', 7631, 73);
insert into book (title, price, discount) values ('ultrices aliquet maecenas leo odio condimentum', 6270, 2);
insert into book (title, price, discount) values ('eros elementum', 639, 74);
insert into book (title, price, discount) values ('montes nascetur ridiculus mus', 7261, 94);
insert into book (title, price, discount) values ('lobortis vel dapibus at diam nam tristique', 6679, 75);
insert into book (title, price, discount) values ('eleifend donec', 5581, 1);
insert into book (title, price, discount) values ('porta volutpat erat quisque', 2637, 38);
insert into book (title, price, discount) values ('vestibulum ante ipsum primis', 652, 29);
insert into book (title, price, discount) values ('posuere felis sed', 2993, 95);
insert into book (title, price, discount) values ('vestibulum aliquet', 5308, 71);
insert into book (title, price, discount) values ('parturient montes', 8172, 83);
insert into book (title, price, discount) values ('quam suspendisse potenti nullam porttitor lacus at', 8018, 41);
insert into book (title, price, discount) values ('amet eleifend pede libero quis orci nullam', 1751, 92);
insert into book (title, price, discount) values ('venenatis non sodales sed tincidunt eu', 5157, 12);
insert into book (title, price, discount) values ('pretium nisl ut volutpat sapien arcu', 3656, 66);
insert into book (title, price, discount) values ('erat volutpat in congue', 656, 57);
insert into book (title, price, discount) values ('imperdiet nullam orci', 6875, 37);
insert into book (title, price, discount) values ('curae duis', 4587, 30);
insert into book (title, price, discount) values ('nec condimentum neque sapien placerat ante', 4971, 90);
insert into book (title, price, discount) values ('nisl nunc nisl', 7494, 40);
insert into book (title, price, discount) values ('maecenas rhoncus', 8313, 59);
insert into book (title, price, discount) values ('erat curabitur', 5531, 17);
insert into book (title, price, discount) values ('ut erat', 9692, 46);
insert into book (title, price, discount) values ('nulla ac enim in tempor', 1884, 52);
insert into book (title, price, discount) values ('nulla quisque arcu libero rutrum', 3752, 23);
insert into book (title, price, discount) values ('nulla ultrices aliquet maecenas leo odio', 8761, 18);
insert into book (title, price, discount) values ('phasellus sit amet erat nulla tempus', 9962, 49);
insert into book (title, price, discount) values ('blandit mi in porttitor', 1109, 14);
insert into book (title, price, discount) values ('purus aliquet at feugiat', 2198, 47);
insert into book (title, price, discount) values ('maecenas leo', 6874, 29);
insert into book (title, price, discount) values ('nec sem duis', 4451, 40);
insert into book (title, price, discount) values ('ligula sit amet eleifend pede libero', 6956, 92);
insert into book (title, price, discount) values ('praesent blandit nam nulla integer', 908, 42);
insert into book (title, price, discount) values ('in ante', 5278, 77);
insert into book (title, price, discount) values ('nascetur ridiculus mus vivamus vestibulum', 9211, 18);
insert into book (title, price, discount) values ('quis justo maecenas rhoncus aliquam lacus', 5517, 82);
insert into book (title, price, discount) values ('adipiscing lorem vitae mattis', 436, 83);
insert into book (title, price, discount) values ('dolor morbi vel lectus in', 7779, 26);
insert into book (title, price, discount) values ('adipiscing lorem vitae mattis nibh ligula nec', 1840, 15);
insert into book (title, price, discount) values ('dapibus duis at velit eu est congue', 8302, 7);
insert into book (title, price, discount) values ('dapibus nulla', 3506, 15);
insert into book (title, price, discount) values ('ac nibh fusce lacus purus aliquet', 7737, 25);
insert into book (title, price, discount) values ('posuere cubilia curae', 1520, 38);
insert into book (title, price, discount) values ('pede libero quis orci', 2914, 1);
insert into book (title, price, discount) values ('mauris eget', 638, 43);
insert into book (title, price, discount) values ('non ligula pellentesque', 6014, 40);
insert into book (title, price, discount) values ('massa quis augue luctus', 7062, 18);
insert into book (title, price, discount) values ('ante ipsum primis', 6751, 81);
insert into book (title, price, discount) values ('sapien dignissim vestibulum vestibulum ante ipsum', 3361, 32);
insert into book (title, price, discount) values ('donec quis orci', 1897, 11);
insert into book (title, price, discount) values ('vestibulum ante', 7194, 13);
insert into book (title, price, discount) values ('curabitur at', 1210, 79);
insert into book (title, price, discount) values ('nulla nisl', 2602, 10);
insert into book (title, price, discount) values ('mauris ullamcorper purus', 938, 18);
insert into book (title, price, discount) values ('est quam', 5279, 74);
insert into book (title, price, discount) values ('sit amet eleifend pede libero quis', 8918, 98);
insert into book (title, price, discount) values ('nisl duis ac nibh fusce', 306, 50);
insert into book (title, price, discount) values ('ipsum ac tellus', 3436, 73);
insert into book (title, price, discount) values ('fusce congue diam id ornare', 8558, 55);
insert into book (title, price, discount) values ('in felis eu sapien', 3881, 35);
insert into book (title, price, discount) values ('ipsum primis in faucibus', 5662, 71);
insert into book (title, price, discount) values ('curabitur gravida', 2011, 63);
insert into book (title, price, discount) values ('sed vestibulum sit amet cursus', 132, 27);
insert into book (title, price, discount) values ('est et tempus semper est', 5584, 23);
insert into book (title, price, discount) values ('mauris eget massa tempor convallis', 9700, 77);
insert into book (title, price, discount) values ('purus eu magna vulputate luctus cum', 4404, 79);
insert into book (title, price, discount) values ('sed tristique in tempus sit amet', 467, 45);
insert into book (title, price, discount) values ('sed augue aliquam erat', 7583, 47);
insert into book (title, price, discount) values ('dapibus dolor', 7363, 67);
insert into book (title, price, discount) values ('condimentum neque sapien placerat ante nulla', 5275, 34);
insert into book (title, price, discount) values ('convallis tortor risus dapibus augue', 6937, 89);
insert into book (title, price, discount) values ('eros suspendisse', 9236, 96);
insert into book (title, price, discount) values ('eu magna', 9432, 12);
insert into book (title, price, discount) values ('posuere cubilia curae mauris viverra', 75, 68);
insert into book (title, price, discount) values ('etiam pretium iaculis justo in hac', 4856, 32);
insert into book (title, price, discount) values ('eu massa donec dapibus duis', 8310, 93);
insert into book (title, price, discount) values ('pellentesque volutpat dui maecenas tristique', 4847, 42);
insert into book (title, price, discount) values ('rhoncus sed vestibulum sit amet cursus id', 4356, 8);
insert into book (title, price, discount) values ('ac leo pellentesque', 609, 40);
insert into book (title, price, discount) values ('at velit', 5025, 19);
insert into book (title, price, discount) values ('mi sit amet lobortis sapien sapien non', 6964, 3);
insert into book (title, price, discount) values ('sociis natoque penatibus', 536, 38);
insert into book (title, price, discount) values ('bibendum imperdiet nullam', 1967, 96);
insert into book (title, price, discount) values ('nam dui proin leo odio', 5650, 91);
insert into book (title, price, discount) values ('tempus sit amet sem fusce consequat nulla', 9838, 25);
insert into book (title, price, discount) values ('fringilla rhoncus mauris enim leo rhoncus sed', 5729, 21);
insert into book (title, price, discount) values ('consequat ut nulla sed', 2355, 3);
insert into book (title, price, discount) values ('in quam fringilla', 9593, 79);
insert into book (title, price, discount) values ('iaculis diam erat fermentum justo nec', 3208, 83);
insert into book (title, price, discount) values ('pellentesque viverra pede ac diam cras', 3125, 79);
insert into book (title, price, discount) values ('venenatis tristique fusce congue diam', 1106, 90);
insert into book (title, price, discount) values ('eleifend donec ut dolor morbi vel lectus', 7718, 21);
insert into book (title, price, discount) values ('mauris viverra diam vitae quam suspendisse potenti', 7093, 81);
insert into book (title, price, discount) values ('sagittis sapien cum sociis', 1977, 74);
insert into book (title, price, discount) values ('mi nulla ac', 8894, 43);
insert into book (title, price, discount) values ('eu sapien cursus', 559, 18);
insert into book (title, price, discount) values ('erat vestibulum sed', 833, 24);
insert into book (title, price, discount) values ('fermentum justo nec condimentum neque sapien placerat', 4124, 41);
insert into book (title, price, discount) values ('scelerisque mauris sit', 7786, 20);
insert into book (title, price, discount) values ('imperdiet nullam', 9367, 55);
insert into book (title, price, discount) values ('ac consequat metus sapien ut nunc', 4998, 55);
insert into book (title, price, discount) values ('id sapien in sapien', 236, 40);
insert into book (title, price, discount) values ('aliquam quis turpis eget elit sodales', 3257, 23);
insert into book (title, price, discount) values ('cursus urna ut tellus nulla ut', 5600, 80);
insert into book (title, price, discount) values ('adipiscing molestie hendrerit at vulputate vitae', 5394, 62);
insert into book (title, price, discount) values ('tempus vel pede morbi porttitor', 9006, 12);
insert into book (title, price, discount) values ('orci eget orci vehicula condimentum curabitur', 6963, 59);
insert into book (title, price, discount) values ('rhoncus mauris enim leo', 6281, 82);
insert into book (title, price, discount) values ('orci pede venenatis non sodales', 7115, 88);
insert into book (title, price, discount) values ('molestie nibh in lectus pellentesque at', 6141, 5);
insert into book (title, price, discount) values ('odio consequat varius integer', 9859, 43);
insert into book (title, price, discount) values ('habitasse platea', 8093, 30);
insert into book (title, price, discount) values ('luctus tincidunt nulla', 7742, 40);
insert into book (title, price, discount) values ('porta volutpat quam pede lobortis ligula sit', 7364, 58);
insert into book (title, price, discount) values ('mauris vulputate elementum nullam varius', 8019, 79);
insert into book (title, price, discount) values ('mauris sit amet eros suspendisse accumsan tortor', 5855, 38);
insert into book (title, price, discount) values ('praesent blandit', 4280, 96);
insert into book (title, price, discount) values ('feugiat et eros vestibulum ac est lacinia', 3301, 71);
insert into book (title, price, discount) values ('in hac habitasse platea dictumst maecenas', 8774, 98);
insert into book (title, price, discount) values ('sit amet justo morbi ut odio cras', 4051, 33);
insert into book (title, price, discount) values ('amet sapien dignissim vestibulum vestibulum', 8587, 7);
insert into book (title, price, discount) values ('id turpis integer aliquet massa id', 9804, 56);
insert into book (title, price, discount) values ('donec pharetra', 9812, 60);
insert into book (title, price, discount) values ('faucibus orci luctus et', 396, 66);
insert into book (title, price, discount) values ('porttitor pede justo eu', 9890, 90);
insert into book (title, price, discount) values ('dolor vel est donec', 6015, 51);
insert into book (title, price, discount) values ('massa tempor convallis', 6442, 65);
insert into book (title, price, discount) values ('donec quis orci eget orci', 4061, 93);
insert into book (title, price, discount) values ('et ultrices posuere cubilia curae nulla', 919, 97);
insert into book (title, price, discount) values ('nulla ut erat id', 9670, 66);
insert into book (title, price, discount) values ('posuere cubilia curae duis faucibus accumsan', 4990, 16);
insert into book (title, price, discount) values ('at turpis a pede posuere', 1347, 77);
insert into book (title, price, discount) values ('eu sapien cursus', 9230, 98);
insert into book (title, price, discount) values ('duis at velit', 9950, 97);
insert into book (title, price, discount) values ('eu est', 4793, 55);
insert into book (title, price, discount) values ('non ligula pellentesque ultrices', 9479, 83);
insert into book (title, price, discount) values ('fusce posuere felis', 9959, 64);
insert into book (title, price, discount) values ('eros elementum pellentesque', 4978, 65);
insert into book (title, price, discount) values ('tincidunt eu felis fusce', 7540, 21);
insert into book (title, price, discount) values ('convallis nunc proin at turpis', 665, 27);
insert into book (title, price, discount) values ('at velit eu est congue elementum in', 2163, 75);
insert into book (title, price, discount) values ('dolor sit amet consectetuer adipiscing elit proin', 3914, 12);
insert into book (title, price, discount) values ('at velit eu est congue elementum in', 3265, 93);
insert into book (title, price, discount) values ('fusce posuere felis sed lacus morbi sem', 1436, 89);
insert into book (title, price, discount) values ('quam pede lobortis', 4519, 38);
insert into book (title, price, discount) values ('ipsum praesent blandit lacinia erat', 2058, 63);
insert into book (title, price, discount) values ('praesent lectus', 1470, 4);
insert into book (title, price, discount) values ('ut volutpat sapien', 7573, 28);
insert into book (title, price, discount) values ('velit nec nisi vulputate nonummy maecenas', 3363, 13);
insert into book (title, price, discount) values ('vulputate ut ultrices vel augue vestibulum', 292, 23);
insert into book (title, price, discount) values ('mauris morbi non lectus', 831, 98);
insert into book (title, price, discount) values ('convallis nunc', 4457, 44);
insert into book (title, price, discount) values ('nisl nunc rhoncus', 299, 47);
insert into book (title, price, discount) values ('adipiscing lorem', 1416, 94);
insert into book (title, price, discount) values ('at diam', 7520, 96);
insert into book (title, price, discount) values ('auctor gravida sem praesent', 8588, 85);
insert into book (title, price, discount) values ('sem praesent', 2353, 31);
insert into book (title, price, discount) values ('tincidunt in leo', 2409, 72);
insert into book (title, price, discount) values ('donec dapibus duis at', 3290, 99);
insert into book (title, price, discount) values ('id justo', 7202, 31);
insert into book (title, price, discount) values ('eleifend donec', 7618, 51);
insert into book (title, price, discount) values ('aliquam non mauris', 5656, 3);
insert into book (title, price, discount) values ('libero non mattis pulvinar', 2258, 92);
insert into book (title, price, discount) values ('fermentum donec', 1433, 81);
insert into book (title, price, discount) values ('orci luctus et', 5899, 93);
insert into book (title, price, discount) values ('mauris ullamcorper purus sit amet nulla quisque', 1504, 16);
insert into book (title, price, discount) values ('phasellus id sapien in', 7441, 6);
insert into book (title, price, discount) values ('ac consequat', 1876, 78);
insert into book (title, price, discount) values ('sit amet', 3927, 43);
insert into book (title, price, discount) values ('id lobortis convallis tortor', 318, 74);
insert into book (title, price, discount) values ('at velit vivamus vel nulla eget eros', 3085, 86);
insert into book (title, price, discount) values ('nibh quisque id justo sit amet sapien', 3233, 43);
insert into book (title, price, discount) values ('egestas metus aenean fermentum donec ut', 4559, 71);
insert into book (title, price, discount) values ('volutpat eleifend', 4283, 78);
insert into book (title, price, discount) values ('praesent blandit nam nulla integer pede', 9684, 86);
insert into book (title, price, discount) values ('volutpat erat', 8276, 61);
insert into book (title, price, discount) values ('donec ut mauris eget massa', 270, 8);
insert into book (title, price, discount) values ('bibendum imperdiet nullam', 6720, 71);
insert into book (title, price, discount) values ('ut at dolor quis odio', 6334, 85);
insert into book (title, price, discount) values ('morbi a ipsum integer a', 2735, 91);
insert into book (title, price, discount) values ('non velit nec nisi vulputate nonummy maecenas', 3549, 69);
insert into book (title, price, discount) values ('eget semper rutrum nulla', 2338, 55);
insert into book (title, price, discount) values ('aenean auctor', 8616, 57);
insert into book (title, price, discount) values ('molestie hendrerit at', 90, 69);
insert into book (title, price, discount) values ('quam pharetra magna ac consequat metus sapien', 3960, 36);
insert into book (title, price, discount) values ('mi pede malesuada in imperdiet et commodo', 3770, 68);
insert into book (title, price, discount) values ('lectus suspendisse potenti in eleifend', 394, 89);
insert into book (title, price, discount) values ('tempor turpis nec euismod scelerisque', 1218, 26);
insert into book (title, price, discount) values ('aenean auctor gravida sem praesent id', 829, 71);
insert into book (title, price, discount) values ('lectus pellentesque', 1599, 1);
insert into book (title, price, discount) values ('parturient montes', 3074, 99);
insert into book (title, price, discount) values ('pellentesque ultrices phasellus id sapien in', 3380, 92);
insert into book (title, price, discount) values ('dolor sit amet consectetuer adipiscing', 3572, 68);
insert into book (title, price, discount) values ('ante ipsum primis in faucibus orci', 5901, 85);
insert into book (title, price, discount) values ('luctus et ultrices posuere', 3674, 63);
insert into book (title, price, discount) values ('integer pede justo lacinia eget', 5064, 2);
insert into book (title, price, discount) values ('odio in hac habitasse platea dictumst maecenas', 6276, 43);
insert into book (title, price, discount) values ('et ultrices posuere cubilia curae donec', 1283, 13);
insert into book (title, price, discount) values ('eget massa tempor', 2119, 89);
insert into book (title, price, discount) values ('eu est congue elementum', 7269, 86);
insert into book (title, price, discount) values ('luctus rutrum nulla', 3315, 67);
insert into book (title, price, discount) values ('lorem ipsum dolor sit amet consectetuer', 5000, 26);
insert into book (title, price, discount) values ('non mauris morbi non lectus', 7070, 57);
insert into book (title, price, discount) values ('vitae nisl aenean lectus pellentesque', 2516, 9);
insert into book (title, price, discount) values ('congue risus', 9482, 24);
insert into book (title, price, discount) values ('habitasse platea dictumst etiam faucibus', 38, 10);
insert into book (title, price, discount) values ('lectus aliquam sit amet diam in magna', 6207, 63);
insert into book (title, price, discount) values ('in felis donec semper', 2912, 18);
insert into book (title, price, discount) values ('donec ut', 5815, 83);
insert into book (title, price, discount) values ('erat eros', 4396, 65);
insert into book (title, price, discount) values ('elementum pellentesque quisque porta volutpat erat', 4360, 35);
insert into book (title, price, discount) values ('donec quis orci eget orci vehicula condimentum', 7332, 82);
insert into book (title, price, discount) values ('nisi at nibh in hac habitasse', 4963, 39);
insert into book (title, price, discount) values ('ultrices aliquet maecenas leo', 3872, 86);
insert into book (title, price, discount) values ('tellus in sagittis dui vel', 8582, 59);
insert into book (title, price, discount) values ('enim leo', 9126, 27);
insert into book (title, price, discount) values ('in tempor turpis nec euismod', 5705, 8);
insert into book (title, price, discount) values ('pretium nisl ut volutpat sapien arcu sed', 3101, 81);
insert into book (title, price, discount) values ('diam nam tristique tortor eu pede', 2485, 39);
insert into book (title, price, discount) values ('viverra dapibus nulla', 8125, 18);
insert into book (title, price, discount) values ('luctus et', 568, 28);
insert into book (title, price, discount) values ('luctus nec molestie sed', 8785, 6);
insert into book (title, price, discount) values ('eget rutrum at lorem integer tincidunt', 3135, 72);
insert into book (title, price, discount) values ('ullamcorper augue a suscipit nulla elit ac', 3294, 80);
insert into book (title, price, discount) values ('duis ac nibh fusce', 7679, 62);
insert into book (title, price, discount) values ('adipiscing elit proin interdum mauris non ligula', 2097, 10);
insert into book (title, price, discount) values ('mauris viverra diam vitae quam suspendisse potenti', 6812, 85);
insert into book (title, price, discount) values ('amet consectetuer adipiscing', 6889, 45);
insert into book (title, price, discount) values ('accumsan tortor quis turpis sed ante', 9483, 68);
insert into book (title, price, discount) values ('morbi porttitor lorem', 193, 55);
insert into book (title, price, discount) values ('vitae nisl aenean lectus pellentesque eget', 8413, 74);
insert into book (title, price, discount) values ('maecenas rhoncus aliquam lacus morbi', 241, 70);
insert into book (title, price, discount) values ('vivamus in', 6314, 45);
insert into book (title, price, discount) values ('volutpat convallis morbi odio odio', 5864, 1);
insert into book (title, price, discount) values ('justo morbi ut odio cras mi pede', 5254, 71);
insert into book (title, price, discount) values ('in faucibus orci luctus', 2973, 55);
insert into book (title, price, discount) values ('nibh in quis justo', 606, 77);
insert into book (title, price, discount) values ('feugiat non pretium quis lectus suspendisse potenti', 9268, 43);
insert into book (title, price, discount) values ('ligula vehicula consequat', 7422, 54);
insert into book (title, price, discount) values ('nunc rhoncus dui vel sem', 2423, 8);
insert into book (title, price, discount) values ('velit eu est congue', 3705, 3);
insert into book (title, price, discount) values ('sapien a libero nam dui proin leo', 3555, 70);
insert into book (title, price, discount) values ('quis augue luctus tincidunt nulla', 684, 82);
insert into book (title, price, discount) values ('turpis elementum ligula vehicula', 4681, 72);
insert into book (title, price, discount) values ('nulla sed vel enim sit amet', 36, 99);
insert into book (title, price, discount) values ('pulvinar nulla', 1955, 5);
insert into book (title, price, discount) values ('ante ipsum primis in faucibus', 3888, 52);
insert into book (title, price, discount) values ('amet consectetuer adipiscing elit proin interdum', 4551, 97);
insert into book (title, price, discount) values ('molestie hendrerit', 648, 34);
insert into book (title, price, discount) values ('mus vivamus vestibulum', 4157, 51);
insert into book (title, price, discount) values ('consequat dui nec nisi volutpat eleifend', 6134, 73);
insert into book (title, price, discount) values ('montes nascetur ridiculus mus vivamus', 6284, 14);
insert into book (title, price, discount) values ('cubilia curae', 5959, 64);
insert into book (title, price, discount) values ('non ligula pellentesque ultrices phasellus id', 9025, 73);
insert into book (title, price, discount) values ('ligula pellentesque ultrices phasellus', 3041, 11);
insert into book (title, price, discount) values ('vestibulum vestibulum ante ipsum primis in', 6610, 18);
insert into book (title, price, discount) values ('congue etiam justo', 1998, 23);
insert into book (title, price, discount) values ('pharetra magna ac consequat metus sapien', 2110, 69);
insert into book (title, price, discount) values ('lobortis sapien', 8315, 53);
insert into book (title, price, discount) values ('morbi sem mauris laoreet ut rhoncus aliquet', 4332, 22);
insert into book (title, price, discount) values ('sed accumsan', 5136, 46);
insert into book (title, price, discount) values ('ut rhoncus', 8099, 70);
insert into book (title, price, discount) values ('aliquam sit amet diam in magna', 366, 84);
insert into book (title, price, discount) values ('aliquam convallis nunc', 464, 76);
insert into book (title, price, discount) values ('posuere nonummy integer non velit donec diam', 9859, 29);
insert into book (title, price, discount) values ('nulla ac enim in', 4463, 81);
insert into book (title, price, discount) values ('at nunc', 7983, 94);
insert into book (title, price, discount) values ('eu felis fusce posuere felis sed', 710, 4);
insert into book (title, price, discount) values ('nibh in hac habitasse platea dictumst aliquam', 8554, 45);
insert into book (title, price, discount) values ('risus semper', 1589, 12);
insert into book (title, price, discount) values ('congue eget', 4725, 56);
insert into book (title, price, discount) values ('tortor sollicitudin mi sit amet lobortis sapien', 4776, 70);
insert into book (title, price, discount) values ('vulputate luctus cum sociis', 7143, 2);
insert into book (title, price, discount) values ('dictumst aliquam', 5192, 6);
insert into book (title, price, discount) values ('eleifend luctus ultricies eu nibh quisque', 7196, 40);
insert into book (title, price, discount) values ('in felis eu sapien', 3674, 37);
insert into book (title, price, discount) values ('pellentesque at nulla suspendisse', 9394, 3);
insert into book (title, price, discount) values ('ante ipsum primis in', 6247, 51);
insert into book (title, price, discount) values ('sit amet justo morbi ut odio', 291, 92);
insert into book (title, price, discount) values ('nulla integer', 3683, 45);
insert into book (title, price, discount) values ('tellus in sagittis dui vel nisl duis', 150, 72);
insert into book (title, price, discount) values ('vivamus vel', 5639, 59);
insert into book (title, price, discount) values ('amet sapien dignissim vestibulum vestibulum ante', 3673, 72);
insert into book (title, price, discount) values ('eleifend donec ut dolor', 4297, 84);
insert into book (title, price, discount) values ('vitae ipsum aliquam non mauris morbi', 6632, 91);
insert into book (title, price, discount) values ('lectus in est risus auctor sed', 8109, 5);
insert into book (title, price, discount) values ('eget semper', 3542, 59);
insert into book (title, price, discount) values ('nibh fusce lacus', 9446, 11);
insert into book (title, price, discount) values ('pretium iaculis justo in hac', 2945, 37);
insert into book (title, price, discount) values ('sit amet cursus id turpis', 9032, 47);
insert into book (title, price, discount) values ('nunc viverra dapibus nulla suscipit ligula', 6711, 42);
insert into book (title, price, discount) values ('lacus morbi sem mauris laoreet', 5978, 86);
insert into book (title, price, discount) values ('id turpis integer aliquet', 9894, 32);
insert into book (title, price, discount) values ('quam a odio in', 6780, 98);
insert into book (title, price, discount) values ('metus aenean fermentum donec ut mauris eget', 2854, 58);
insert into book (title, price, discount) values ('quam pharetra magna ac consequat metus sapien', 2394, 57);
insert into book (title, price, discount) values ('nulla sed accumsan felis', 4590, 89);
insert into book (title, price, discount) values ('neque duis bibendum morbi non', 4628, 58);
insert into book (title, price, discount) values ('justo nec', 5783, 90);
insert into book (title, price, discount) values ('libero nam dui proin leo', 9588, 90);
insert into book (title, price, discount) values ('eleifend donec ut', 7697, 32);
insert into book (title, price, discount) values ('aliquet ultrices erat tortor sollicitudin mi', 6021, 46);
insert into book (title, price, discount) values ('lectus in quam fringilla rhoncus mauris enim', 9727, 60);
insert into book (title, price, discount) values ('adipiscing elit proin interdum mauris non ligula', 1983, 52);
insert into book (title, price, discount) values ('dis parturient montes nascetur ridiculus mus', 5065, 71);
insert into book (title, price, discount) values ('enim blandit mi in porttitor pede justo', 2471, 27);
insert into book (title, price, discount) values ('pharetra magna ac consequat metus', 8577, 73);
insert into book (title, price, discount) values ('risus dapibus augue', 8145, 81);
insert into book (title, price, discount) values ('morbi vestibulum velit id pretium iaculis diam', 4308, 10);
insert into book (title, price, discount) values ('dolor sit amet consectetuer adipiscing elit', 2218, 80);
insert into book (title, price, discount) values ('orci luctus et ultrices posuere', 7255, 91);
insert into book (title, price, discount) values ('suspendisse potenti cras in purus eu', 9871, 64);
insert into book (title, price, discount) values ('arcu libero rutrum', 8763, 42);
insert into book (title, price, discount) values ('sed magna at nunc commodo placerat praesent', 8606, 38);
insert into book (title, price, discount) values ('pede justo lacinia', 8495, 82);
insert into book (title, price, discount) values ('et ultrices posuere cubilia', 86, 85);
insert into book (title, price, discount) values ('augue a suscipit nulla elit ac nulla', 3633, 12);
insert into book (title, price, discount) values ('non mi integer ac neque', 603, 97);
insert into book (title, price, discount) values ('nec euismod scelerisque', 5747, 31);
insert into book (title, price, discount) values ('cras pellentesque volutpat dui maecenas', 1695, 95);
insert into book (title, price, discount) values ('vestibulum sit amet cursus id turpis integer', 3161, 61);
insert into book (title, price, discount) values ('eget massa tempor convallis nulla neque libero', 1940, 16);
insert into book (title, price, discount) values ('turpis sed ante', 1720, 96);
insert into book (title, price, discount) values ('eu felis fusce', 2420, 41);
insert into book (title, price, discount) values ('quam turpis adipiscing lorem', 303, 34);
insert into book (title, price, discount) values ('pede ac diam cras', 3548, 6);
insert into book (title, price, discount) values ('lobortis est', 4252, 10);
insert into book (title, price, discount) values ('vel sem sed sagittis nam', 4705, 71);
insert into book (title, price, discount) values ('turpis a', 6035, 21);
insert into book (title, price, discount) values ('nulla sed', 9215, 24);
insert into book (title, price, discount) values ('pulvinar lobortis est phasellus', 7793, 17);
insert into book (title, price, discount) values ('vel augue vestibulum ante', 5730, 2);
insert into book (title, price, discount) values ('nunc purus phasellus', 9800, 94);
insert into book (title, price, discount) values ('amet consectetuer adipiscing elit', 4242, 63);
insert into book (title, price, discount) values ('ornare imperdiet sapien urna pretium nisl ut', 6770, 86);
insert into book (title, price, discount) values ('in porttitor pede justo eu', 937, 12);
insert into book (title, price, discount) values ('dictumst etiam', 9986, 72);
insert into book (title, price, discount) values ('lorem ipsum dolor sit amet', 251, 17);
insert into book (title, price, discount) values ('diam erat fermentum justo nec condimentum neque', 6942, 21);
insert into book (title, price, discount) values ('elementum in', 6186, 68);
insert into book (title, price, discount) values ('interdum mauris ullamcorper purus sit amet nulla', 5440, 88);
insert into book (title, price, discount) values ('convallis eget eleifend', 4408, 63);
insert into book (title, price, discount) values ('non lectus aliquam sit amet', 9331, 1);
insert into book (title, price, discount) values ('quam turpis adipiscing lorem vitae mattis', 2623, 8);
insert into book (title, price, discount) values ('ipsum integer a nibh', 229, 19);
insert into book (title, price, discount) values ('sed justo pellentesque viverra pede', 3093, 23);
insert into book (title, price, discount) values ('viverra diam', 4871, 92);
insert into book (title, price, discount) values ('id lobortis convallis tortor risus', 8923, 37);
insert into book (title, price, discount) values ('praesent lectus vestibulum quam sapien varius ut', 7293, 63);
insert into book (title, price, discount) values ('ut dolor morbi', 9283, 86);
insert into book (title, price, discount) values ('aenean sit amet justo', 8070, 79);
insert into book (title, price, discount) values ('ut nunc vestibulum ante ipsum', 307, 33);
insert into book (title, price, discount) values ('ut at dolor', 3520, 33);
insert into book (title, price, discount) values ('in tempus sit amet sem fusce', 5374, 25);
insert into book (title, price, discount) values ('curae nulla dapibus dolor vel', 4623, 44);
insert into book (title, price, discount) values ('enim in tempor turpis', 1376, 77);
insert into book (title, price, discount) values ('interdum in ante', 2025, 71);
insert into book (title, price, discount) values ('placerat praesent blandit nam', 9894, 9);
insert into book (title, price, discount) values ('donec pharetra magna', 3805, 37);
insert into book (title, price, discount) values ('consequat varius integer ac leo', 8072, 6);
insert into book (title, price, discount) values ('elementum ligula vehicula consequat morbi a', 8788, 93);
insert into book (title, price, discount) values ('a suscipit nulla', 3549, 64);
insert into book (title, price, discount) values ('sit amet eleifend pede', 2185, 42);
insert into book (title, price, discount) values ('venenatis tristique fusce congue diam id', 9968, 7);
insert into book (title, price, discount) values ('lectus aliquam sit amet diam in magna', 621, 82);
insert into book (title, price, discount) values ('habitasse platea dictumst', 9242, 76);
insert into book (title, price, discount) values ('consequat varius integer ac leo pellentesque', 9036, 37);
insert into book (title, price, discount) values ('ultrices vel augue vestibulum ante ipsum', 1046, 19);
insert into book (title, price, discount) values ('hendrerit at vulputate vitae nisl aenean lectus', 3532, 98);
insert into book (title, price, discount) values ('vestibulum rutrum rutrum neque aenean auctor gravida', 4311, 10);
insert into book (title, price, discount) values ('semper est quam pharetra', 9565, 10);
insert into book (title, price, discount) values ('sit amet', 8065, 38);
insert into book (title, price, discount) values ('porta volutpat quam pede', 2825, 63);
insert into book (title, price, discount) values ('eget congue eget semper rutrum nulla', 6168, 38);
insert into book (title, price, discount) values ('quis augue', 595, 61);
insert into book (title, price, discount) values ('diam vitae', 8275, 51);
insert into book (title, price, discount) values ('turpis donec posuere', 9877, 35);
insert into book (title, price, discount) values ('at feugiat non pretium quis lectus', 2171, 55);
insert into book (title, price, discount) values ('justo sollicitudin', 6687, 15);
insert into book (title, price, discount) values ('nunc vestibulum ante ipsum primis in', 3433, 68);
insert into book (title, price, discount) values ('curae mauris viverra', 2809, 58);
insert into book (title, price, discount) values ('ut erat curabitur gravida', 1118, 15);
insert into book (title, price, discount) values ('nulla facilisi cras non velit nec nisi', 5693, 76);
insert into book (title, price, discount) values ('placerat praesent blandit nam nulla integer', 7952, 17);
insert into book (title, price, discount) values ('tristique tortor eu', 6390, 5);
insert into book (title, price, discount) values ('ultricies eu nibh quisque id justo', 7792, 88);
insert into book (title, price, discount) values ('morbi quis tortor id', 9579, 84);
insert into book (title, price, discount) values ('ultrices mattis', 7724, 45);
insert into book (title, price, discount) values ('imperdiet et', 3375, 93);
insert into book (title, price, discount) values ('quis odio', 6386, 63);
insert into book (title, price, discount) values ('imperdiet nullam orci pede venenatis', 1580, 17);
insert into book (title, price, discount) values ('in hac habitasse platea dictumst etiam faucibus', 2844, 40);
insert into book (title, price, discount) values ('donec quis orci', 9513, 3);
insert into book (title, price, discount) values ('vitae consectetuer', 3777, 86);
insert into book (title, price, discount) values ('tortor risus dapibus augue vel accumsan tellus', 3639, 54);
insert into book (title, price, discount) values ('pede lobortis', 3134, 61);
insert into book (title, price, discount) values ('luctus et ultrices posuere', 8737, 11);
insert into book (title, price, discount) values ('lacinia nisi venenatis tristique fusce congue diam', 8475, 59);
insert into book (title, price, discount) values ('elit proin risus praesent lectus', 5413, 70);
insert into book (title, price, discount) values ('erat curabitur gravida nisi at nibh in', 2816, 36);
insert into book (title, price, discount) values ('quam sollicitudin', 5073, 44);
insert into book (title, price, discount) values ('morbi porttitor lorem id', 8257, 60);
insert into book (title, price, discount) values ('fringilla rhoncus mauris enim leo', 2277, 91);
insert into book (title, price, discount) values ('velit nec nisi vulputate nonummy maecenas', 7534, 28);
insert into book (title, price, discount) values ('condimentum id luctus nec molestie sed justo', 430, 58);
insert into book (title, price, discount) values ('volutpat convallis morbi odio odio elementum', 9843, 20);
insert into book (title, price, discount) values ('auctor gravida sem', 4740, 74);
insert into book (title, price, discount) values ('ac consequat metus sapien ut nunc vestibulum', 153, 49);
insert into book (title, price, discount) values ('a pede', 1892, 99);
insert into book (title, price, discount) values ('in est risus', 9686, 33);
insert into book (title, price, discount) values ('lorem ipsum', 8247, 80);
insert into book (title, price, discount) values ('integer tincidunt ante vel', 5493, 32);
insert into book (title, price, discount) values ('vitae ipsum aliquam non mauris morbi non', 7179, 93);
insert into book (title, price, discount) values ('interdum eu', 4180, 20);
insert into book (title, price, discount) values ('rhoncus dui', 13, 78);
insert into book (title, price, discount) values ('fusce consequat', 7285, 59);
insert into book (title, price, discount) values ('rutrum neque aenean', 5516, 47);
insert into book (title, price, discount) values ('dui nec nisi volutpat eleifend', 7310, 0);
insert into book (title, price, discount) values ('ligula pellentesque ultrices phasellus', 7065, 32);
insert into book (title, price, discount) values ('dictumst etiam', 3112, 2);
insert into book (title, price, discount) values ('quis justo maecenas rhoncus aliquam lacus morbi', 689, 72);
insert into book (title, price, discount) values ('eget nunc donec', 1157, 1);
insert into book (title, price, discount) values ('ac enim in tempor turpis', 923, 59);
insert into book (title, price, discount) values ('lectus in est risus', 9007, 8);
insert into book (title, price, discount) values ('eget vulputate ut ultrices vel augue vestibulum', 9884, 42);
insert into book (title, price, discount) values ('vulputate nonummy', 7490, 25);
insert into book (title, price, discount) values ('molestie nibh in lectus pellentesque at', 2022, 86);
insert into book (title, price, discount) values ('vivamus in felis eu sapien cursus', 3449, 66);
insert into book (title, price, discount) values ('pharetra magna ac consequat', 3080, 11);
insert into book (title, price, discount) values ('ut mauris eget massa tempor convallis nulla', 8856, 28);
insert into book (title, price, discount) values ('fusce posuere felis', 5212, 10);
insert into book (title, price, discount) values ('in ante vestibulum ante ipsum primis in', 9985, 24);
insert into book (title, price, discount) values ('sed nisl nunc rhoncus', 1529, 26);
insert into book (title, price, discount) values ('ut rhoncus aliquet', 5071, 99);
insert into book (title, price, discount) values ('eleifend luctus ultricies', 1050, 69);
insert into book (title, price, discount) values ('rhoncus aliquam lacus morbi quis', 337, 63);
insert into book (title, price, discount) values ('quis turpis sed', 4367, 45);
insert into book (title, price, discount) values ('pulvinar nulla', 5819, 62);
insert into book (title, price, discount) values ('donec vitae nisi nam', 6402, 30);
insert into book (title, price, discount) values ('dolor morbi vel lectus in quam fringilla', 6204, 6);
insert into book (title, price, discount) values ('nulla neque libero convallis eget eleifend', 6512, 93);
insert into book (title, price, discount) values ('neque vestibulum eget vulputate', 6949, 53);
insert into book (title, price, discount) values ('velit nec nisi vulputate nonummy', 5469, 94);
insert into book (title, price, discount) values ('tincidunt nulla mollis molestie', 8951, 13);
insert into book (title, price, discount) values ('pede libero quis orci nullam molestie', 1091, 79);
insert into book (title, price, discount) values ('venenatis non sodales sed tincidunt', 9097, 22);
insert into book (title, price, discount) values ('a ipsum integer a', 6823, 6);
insert into book (title, price, discount) values ('ut blandit non interdum in ante vestibulum', 7316, 62);
insert into book (title, price, discount) values ('ultrices posuere cubilia', 9581, 47);
insert into book (title, price, discount) values ('platea dictumst aliquam augue', 986, 66);
insert into book (title, price, discount) values ('venenatis turpis enim blandit mi in', 6240, 43);
insert into book (title, price, discount) values ('nulla ac enim in tempor', 3340, 92);
insert into book (title, price, discount) values ('luctus et ultrices posuere cubilia curae mauris', 2640, 58);
insert into book (title, price, discount) values ('mattis pulvinar nulla pede ullamcorper', 6195, 96);
insert into book (title, price, discount) values ('augue vestibulum ante ipsum primis in', 526, 7);
insert into book (title, price, discount) values ('nulla integer', 9500, 8);
insert into book (title, price, discount) values ('ipsum primis in faucibus', 8507, 91);
insert into book (title, price, discount) values ('pede lobortis ligula', 9752, 61);
insert into book (title, price, discount) values ('morbi quis tortor id nulla', 5802, 43);
insert into book (title, price, discount) values ('vel ipsum praesent blandit lacinia', 8425, 51);
insert into book (title, price, discount) values ('ut massa quis augue', 3245, 20);
insert into book (title, price, discount) values ('lacinia aenean sit amet justo', 6352, 15);
insert into book (title, price, discount) values ('a pede posuere nonummy integer non velit', 2526, 48);
insert into book (title, price, discount) values ('at nibh in hac habitasse', 8730, 72);
insert into book (title, price, discount) values ('ut dolor morbi vel lectus in quam', 6458, 54);
insert into book (title, price, discount) values ('nullam molestie nibh in lectus', 5455, 97);
insert into book (title, price, discount) values ('donec posuere metus', 2853, 3);
insert into book (title, price, discount) values ('ligula vehicula consequat morbi a ipsum', 6774, 34);
insert into book (title, price, discount) values ('et ultrices posuere cubilia', 9075, 94);
insert into book (title, price, discount) values ('at nibh', 5462, 45);
insert into book (title, price, discount) values ('neque libero convallis', 2232, 96);
insert into book (title, price, discount) values ('lacus curabitur at ipsum ac tellus semper', 7290, 14);
insert into book (title, price, discount) values ('eu tincidunt in leo', 5086, 22);
insert into book (title, price, discount) values ('tortor risus dapibus augue', 7951, 80);
insert into book (title, price, discount) values ('erat quisque erat', 6085, 9);
insert into book (title, price, discount) values ('varius integer', 9017, 38);
insert into book (title, price, discount) values ('amet eleifend pede libero', 3595, 16);
insert into book (title, price, discount) values ('bibendum felis sed interdum venenatis', 6878, 76);
insert into book (title, price, discount) values ('montes nascetur ridiculus mus etiam vel augue', 3706, 18);
insert into book (title, price, discount) values ('pede justo eu massa donec dapibus duis', 8177, 40);
insert into book (title, price, discount) values ('lacus at velit vivamus vel', 5626, 23);
insert into book (title, price, discount) values ('ut erat', 155, 20);
insert into book (title, price, discount) values ('felis donec', 9192, 30);
insert into book (title, price, discount) values ('amet diam in', 4941, 37);
insert into book (title, price, discount) values ('cras pellentesque volutpat dui maecenas tristique', 967, 86);
insert into book (title, price, discount) values ('sapien dignissim', 2001, 24);
insert into book (title, price, discount) values ('sit amet nunc viverra dapibus nulla suscipit', 3367, 39);
insert into book (title, price, discount) values ('auctor gravida sem praesent id', 9353, 60);
insert into book (title, price, discount) values ('eget nunc', 4408, 38);
insert into book (title, price, discount) values ('vivamus metus arcu adipiscing molestie hendrerit at', 3842, 98);
insert into book (title, price, discount) values ('orci pede venenatis non sodales', 5955, 70);