DROP TABLE IF EXISTS author;
CREATE TABLE author(
id BIGSERIAL PRIMARY KEY,
first_name VARCHAR(100) NOT NULL,
last_name VARCHAR(100) NOT NULL
);

DROP TABLE IF EXISTS book;
CREATE TABLE book(
id BIGSERIAL PRIMARY KEY,
title VARCHAR(250) NOT NULL,
price INT NOT NULL,
discount INT NOT NULL DEFAULT 0
);

DROP TABLE IF EXISTS book2author;
CREATE TABLE book2author(
id BIGSERIAL PRIMARY KEY,
book_id INT NOT NULL,
author_id INT NOT NULL,
FOREIGN KEY (book_id) REFERENCES book(id),
FOREIGN KEY (author_id) REFERENCES author(id)
);

